import Head from 'next/head'
import ContentVideoBtn from '../components/contentSections/ContetnVideoBtn'
import HeroBanner from '../components/banners/HeroBanner'
import PricingSection from '../components/prices/PricingSection'
import MultipleContent from '../components/contentSections/MultipleContent'
import FaqClassic from '../components/faq/FaqClassic'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <HeroBanner />
      <MultipleContent />
      <ContentVideoBtn />
      <PricingSection />
      <FaqClassic />
    </div>
  )
}
