import Head from 'next/head'
import ChooseUs from '../components/pages/ChooseUs'
import HeroBanner from '../components/pages/HeroBanner'
import PricingSection from '../components/pages/PricingSection'
import Services from '../components/pages/Services'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <HeroBanner />
      <Services />
      <ChooseUs />
      <PricingSection />
      {/* <FeedbackSlider /> */}

    </div>
  )
}
